spring:
#  mysql 配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: tiana
  #redis配置
  redis:
    host: 192.168.107.129
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 300
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
  session:
    store-type: redis
#    timeout: 2000    这些配置的session的过期时间竟然报错了。还是写在启动类的注解里面比较好
    host: 192.168.107.129
    port: 6379


  # 配置热部署的
  devtools:
    restart:
      enabled: true
      exclude: com

mybatis:
  type-aliases-package: com.greentrust.entity

logging:
   classpath: log4j2.xml
server:
  port: 8081

redisCacheKey:
  minerList:
    minerKey: minerlist
    powerKey: powerlist




